import { Header } from "@/components/header";
import { geistMono, geistSans } from "@/fonts";
import "@/globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(geistSans.variable, geistMono.variable, "antialiased")}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
